import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

export const PAPERMINDS_READ_ONLY_PERMISSION_PROFILE = 'papermind-research-read-only';

export async function installCodexPermissionProfile(
  codexHome: string,
  workingDirectory: string,
): Promise<void> {
  const resolvedHome = path.resolve(codexHome);
  const resolvedWorkingDirectory = path.resolve(workingDirectory);
  await Promise.all([
    mkdir(resolvedHome, { recursive: true }),
    mkdir(resolvedWorkingDirectory, { recursive: true }),
  ]);
  const configPath = path.join(resolvedHome, 'config.toml');
  const temporaryPath = `${configPath}.tmp`;
  try {
    await writeFile(temporaryPath, renderCodexPermissionProfile(resolvedWorkingDirectory), {
      encoding: 'utf8',
      mode: 0o600,
    });
    await rename(temporaryPath, configPath);
  } catch (error) {
    await rm(temporaryPath, { force: true }).catch(() => undefined);
    throw error;
  }
}

export function renderCodexPermissionProfile(workingDirectory: string): string {
  const workspaceRoot = path.resolve(workingDirectory).replaceAll('\\', '/');
  const profile = PAPERMINDS_READ_ONLY_PERMISSION_PROFILE;

  return [
    '# Generated by PaperMind. This CODEX_HOME is isolated from other Codex clients.',
    `default_permissions = ${tomlString(profile)}`,
    '',
    `[permissions.${profile}]`,
    'description = "PaperMind research chat: isolated workspace read-only, fixed Codex network."',
    '',
    `[permissions.${profile}.workspace_roots]`,
    `${tomlString(workspaceRoot)} = true`,
    '',
    `[permissions.${profile}.filesystem]`,
    '":root" = "deny"',
    '":minimal" = "read"',
    '":tmpdir" = "deny"',
    '":slash_tmp" = "deny"',
    '',
    `[permissions.${profile}.filesystem.":workspace_roots"]`,
    '"." = "read"',
    '',
    `[permissions.${profile}.network]`,
    'enabled = true',
    'allow_local_binding = false',
    'allow_upstream_proxy = true',
    '',
    `[permissions.${profile}.network.domains]`,
    '"chatgpt.com" = "allow"',
    '',
  ].join('\n');
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}
